require "strscan"
require "active_support"
require "active_support/core_ext"

require "./lib/apodidae/version"
require "./lib/apodidae/prehtml"
require "./lib/apodidae/manager"
require "./lib/apodidae/combine"
require "./lib/apodidae/barb"
require "./lib/apodidae/rachis"
require "./lib/apodidae/helper"
