require "active_support/core_ext"

require "./lib/apodidae/version"
require "./lib/apodidae/prehtml"
require "./lib/apodidae/manager"
require "./lib/apodidae/barb"
require "./lib/apodidae/rachis"
require "./lib/apodidae/edge"
require "./lib/apodidae/connection"
require "./lib/apodidae/inject"
require "./lib/apodidae/helper"
